// Code generated by xmocks; DO NOT EDIT.
package mocks

import (
	"fmt"
	"io/fs"
	"os"
	"runtime"
	"time"

	"github.com/AeonDigital/Go-Core/xbridge/go/bio/bfs"
)

type TestCaseOS struct {
	Name        string
	Env         map[string]string
	Input       any
	Want        any
	WantErr     bool
	ErrContains string
	MockFn      func(m *MockOS)
}

func NewMockOS() *MockOS {
	mock := &MockOS{}
	mock.OnCall = &mockOnCallOS{mock: mock}
	mock.SetReturn = &mockSetReturnOS{mock: mock}
	return mock
}

type MockOS struct {
	CreateFunc        func(name string) (bfs.IFileBridge, error)
	OpenFunc          func(name string) (bfs.IFileBridge, error)
	OpenFileFunc      func(name string, flag int, perm os.FileMode) (bfs.IFileBridge, error)
	CreateTempFunc    func(dir, pattern string) (bfs.IFileBridge, error)
	MkdirFunc         func(name string, perm os.FileMode) error
	MkdirAllFunc      func(path string, perm os.FileMode) error
	RemoveFunc        func(name string) error
	RemoveAllFunc     func(path string) error
	RenameFunc        func(oldpath, newpath string) error
	SymlinkFunc       func(oldname, newname string) error
	ReadlinkFunc      func(name string) (string, error)
	ChmodFunc         func(name string, mode os.FileMode) error
	ChownFunc         func(name string, uid, gid int) error
	LchownFunc        func(name string, uid, gid int) error
	ChtimesFunc       func(name string, atime time.Time, mtime time.Time) error
	StatFunc          func(name string) (bfs.IFileInfoBridge, error)
	LstatFunc         func(name string) (bfs.IFileInfoBridge, error)
	IsNotExistFunc    func(err error) bool
	IsExistFunc       func(err error) bool
	IsPermissionFunc  func(err error) bool
	UserCacheDirFunc  func() (string, error)
	UserConfigDirFunc func() (string, error)
	UserHomeDirFunc   func() (string, error)
	UserLogDirFunc    func() (string, error)
	TempDirFunc       func() string
	ClearenvFunc      func()
	EnvironFunc       func() []string
	ExpandEnvFunc     func(s string) string
	GetenvFunc        func(key string) string
	LookupEnvFunc     func(key string) (string, bool)
	SetenvFunc        func(key, value string) error
	UnsetenvFunc      func(key string) error
	GetpidFunc        func() int
	GetppidFunc       func() int
	GetuidFunc        func() int
	GetgidFunc        func() int
	GeteuidFunc       func() int
	GetegidFunc       func() int
	GetgroupsFunc     func() ([]int, error)
	HostnameFunc      func() (string, error)
	ExecutableFunc    func() (string, error)
	ExitFunc          func(code int)
	GetwdFunc         func() (string, error)
	ChdirFunc         func(dir string) error
	ReadDirFunc       func(name string) ([]fs.DirEntry, error)
	OnCall            *mockOnCallOS
	SetReturn         *mockSetReturnOS
}

func (m *MockOS) panicIfNotConfigured() {
	pc, _, _, ok := runtime.Caller(2)
	methodName := "UnknownMethod"
	if ok {
		fullFnName := runtime.FuncForPC(pc).Name()
		shortName := fullFnName
		for i := len(fullFnName) - 1; i >= 0; i-- {
			if fullFnName[i] == '/' {
				shortName = fullFnName[i+1:]
				break
			}
		}
		methodName = shortName
	}
	panic(fmt.Sprintf("CRITICAL: Mock for %s not configured.", methodName))
}

func (oMock *MockOS) Create(name string) (bfs.IFileBridge, error) {
	if oMock.CreateFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.CreateFunc(name)
}

func (oMock *MockOS) Open(name string) (bfs.IFileBridge, error) {
	if oMock.OpenFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.OpenFunc(name)
}

func (oMock *MockOS) OpenFile(name string, flag int, perm os.FileMode) (bfs.IFileBridge, error) {
	if oMock.OpenFileFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.OpenFileFunc(name, flag, perm)
}

func (oMock *MockOS) CreateTemp(dir, pattern string) (bfs.IFileBridge, error) {
	if oMock.CreateTempFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.CreateTempFunc(dir, pattern)
}

func (oMock *MockOS) Mkdir(name string, perm os.FileMode) error {
	if oMock.MkdirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.MkdirFunc(name, perm)
}

func (oMock *MockOS) MkdirAll(path string, perm os.FileMode) error {
	if oMock.MkdirAllFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.MkdirAllFunc(path, perm)
}

func (oMock *MockOS) Remove(name string) error {
	if oMock.RemoveFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.RemoveFunc(name)
}

func (oMock *MockOS) RemoveAll(path string) error {
	if oMock.RemoveAllFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.RemoveAllFunc(path)
}

func (oMock *MockOS) Rename(oldpath, newpath string) error {
	if oMock.RenameFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.RenameFunc(oldpath, newpath)
}

func (oMock *MockOS) Symlink(oldname, newname string) error {
	if oMock.SymlinkFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.SymlinkFunc(oldname, newname)
}

func (oMock *MockOS) Readlink(name string) (string, error) {
	if oMock.ReadlinkFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ReadlinkFunc(name)
}

func (oMock *MockOS) Chmod(name string, mode os.FileMode) error {
	if oMock.ChmodFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ChmodFunc(name, mode)
}

func (oMock *MockOS) Chown(name string, uid, gid int) error {
	if oMock.ChownFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ChownFunc(name, uid, gid)
}

func (oMock *MockOS) Lchown(name string, uid, gid int) error {
	if oMock.LchownFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.LchownFunc(name, uid, gid)
}

func (oMock *MockOS) Chtimes(name string, atime time.Time, mtime time.Time) error {
	if oMock.ChtimesFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ChtimesFunc(name, atime, mtime)
}

func (oMock *MockOS) Stat(name string) (bfs.IFileInfoBridge, error) {
	if oMock.StatFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.StatFunc(name)
}

func (oMock *MockOS) Lstat(name string) (bfs.IFileInfoBridge, error) {
	if oMock.LstatFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.LstatFunc(name)
}

func (oMock *MockOS) IsNotExist(err error) bool {
	if oMock.IsNotExistFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.IsNotExistFunc(err)
}

func (oMock *MockOS) IsExist(err error) bool {
	if oMock.IsExistFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.IsExistFunc(err)
}

func (oMock *MockOS) IsPermission(err error) bool {
	if oMock.IsPermissionFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.IsPermissionFunc(err)
}

func (oMock *MockOS) UserCacheDir() (string, error) {
	if oMock.UserCacheDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.UserCacheDirFunc()
}

func (oMock *MockOS) UserConfigDir() (string, error) {
	if oMock.UserConfigDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.UserConfigDirFunc()
}

func (oMock *MockOS) UserHomeDir() (string, error) {
	if oMock.UserHomeDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.UserHomeDirFunc()
}

func (oMock *MockOS) UserLogDir() (string, error) {
	if oMock.UserLogDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.UserLogDirFunc()
}

func (oMock *MockOS) TempDir() string {
	if oMock.TempDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.TempDirFunc()
}

func (oMock *MockOS) Clearenv() {
	if oMock.ClearenvFunc == nil {
		oMock.panicIfNotConfigured()
	}
	oMock.ClearenvFunc()
}

func (oMock *MockOS) Environ() []string {
	if oMock.EnvironFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.EnvironFunc()
}

func (oMock *MockOS) ExpandEnv(s string) string {
	if oMock.ExpandEnvFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ExpandEnvFunc(s)
}

func (oMock *MockOS) Getenv(key string) string {
	if oMock.GetenvFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetenvFunc(key)
}

func (oMock *MockOS) LookupEnv(key string) (string, bool) {
	if oMock.LookupEnvFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.LookupEnvFunc(key)
}

func (oMock *MockOS) Setenv(key, value string) error {
	if oMock.SetenvFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.SetenvFunc(key, value)
}

func (oMock *MockOS) Unsetenv(key string) error {
	if oMock.UnsetenvFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.UnsetenvFunc(key)
}

func (oMock *MockOS) Getpid() int {
	if oMock.GetpidFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetpidFunc()
}

func (oMock *MockOS) Getppid() int {
	if oMock.GetppidFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetppidFunc()
}

func (oMock *MockOS) Getuid() int {
	if oMock.GetuidFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetuidFunc()
}

func (oMock *MockOS) Getgid() int {
	if oMock.GetgidFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetgidFunc()
}

func (oMock *MockOS) Geteuid() int {
	if oMock.GeteuidFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GeteuidFunc()
}

func (oMock *MockOS) Getegid() int {
	if oMock.GetegidFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetegidFunc()
}

func (oMock *MockOS) Getgroups() ([]int, error) {
	if oMock.GetgroupsFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetgroupsFunc()
}

func (oMock *MockOS) Hostname() (string, error) {
	if oMock.HostnameFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.HostnameFunc()
}

func (oMock *MockOS) Executable() (string, error) {
	if oMock.ExecutableFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ExecutableFunc()
}

func (oMock *MockOS) Exit(code int) {
	if oMock.ExitFunc == nil {
		oMock.panicIfNotConfigured()
	}
	oMock.ExitFunc(code)
}

func (oMock *MockOS) Getwd() (string, error) {
	if oMock.GetwdFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GetwdFunc()
}

func (oMock *MockOS) Chdir(dir string) error {
	if oMock.ChdirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ChdirFunc(dir)
}

func (oMock *MockOS) ReadDir(name string) ([]fs.DirEntry, error) {
	if oMock.ReadDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ReadDirFunc(name)
}

type mockOnCallOS struct {
	mock *MockOS
}

func (o *mockOnCallOS) Create(fn func(name string) (bfs.IFileBridge, error)) {
	o.mock.CreateFunc = fn
}

func (o *mockOnCallOS) Open(fn func(name string) (bfs.IFileBridge, error)) {
	o.mock.OpenFunc = fn
}

func (o *mockOnCallOS) OpenFile(fn func(name string, flag int, perm os.FileMode) (bfs.IFileBridge, error)) {
	o.mock.OpenFileFunc = fn
}

func (o *mockOnCallOS) CreateTemp(fn func(dir, pattern string) (bfs.IFileBridge, error)) {
	o.mock.CreateTempFunc = fn
}

func (o *mockOnCallOS) Mkdir(fn func(name string, perm os.FileMode) error) {
	o.mock.MkdirFunc = fn
}

func (o *mockOnCallOS) MkdirAll(fn func(path string, perm os.FileMode) error) {
	o.mock.MkdirAllFunc = fn
}

func (o *mockOnCallOS) Remove(fn func(name string) error) {
	o.mock.RemoveFunc = fn
}

func (o *mockOnCallOS) RemoveAll(fn func(path string) error) {
	o.mock.RemoveAllFunc = fn
}

func (o *mockOnCallOS) Rename(fn func(oldpath, newpath string) error) {
	o.mock.RenameFunc = fn
}

func (o *mockOnCallOS) Symlink(fn func(oldname, newname string) error) {
	o.mock.SymlinkFunc = fn
}

func (o *mockOnCallOS) Readlink(fn func(name string) (string, error)) {
	o.mock.ReadlinkFunc = fn
}

func (o *mockOnCallOS) Chmod(fn func(name string, mode os.FileMode) error) {
	o.mock.ChmodFunc = fn
}

func (o *mockOnCallOS) Chown(fn func(name string, uid, gid int) error) {
	o.mock.ChownFunc = fn
}

func (o *mockOnCallOS) Lchown(fn func(name string, uid, gid int) error) {
	o.mock.LchownFunc = fn
}

func (o *mockOnCallOS) Chtimes(fn func(name string, atime time.Time, mtime time.Time) error) {
	o.mock.ChtimesFunc = fn
}

func (o *mockOnCallOS) Stat(fn func(name string) (bfs.IFileInfoBridge, error)) {
	o.mock.StatFunc = fn
}

func (o *mockOnCallOS) Lstat(fn func(name string) (bfs.IFileInfoBridge, error)) {
	o.mock.LstatFunc = fn
}

func (o *mockOnCallOS) IsNotExist(fn func(err error) bool) {
	o.mock.IsNotExistFunc = fn
}

func (o *mockOnCallOS) IsExist(fn func(err error) bool) {
	o.mock.IsExistFunc = fn
}

func (o *mockOnCallOS) IsPermission(fn func(err error) bool) {
	o.mock.IsPermissionFunc = fn
}

func (o *mockOnCallOS) UserCacheDir(fn func() (string, error)) {
	o.mock.UserCacheDirFunc = fn
}

func (o *mockOnCallOS) UserConfigDir(fn func() (string, error)) {
	o.mock.UserConfigDirFunc = fn
}

func (o *mockOnCallOS) UserHomeDir(fn func() (string, error)) {
	o.mock.UserHomeDirFunc = fn
}

func (o *mockOnCallOS) UserLogDir(fn func() (string, error)) {
	o.mock.UserLogDirFunc = fn
}

func (o *mockOnCallOS) TempDir(fn func() string) {
	o.mock.TempDirFunc = fn
}

func (o *mockOnCallOS) Clearenv(fn func()) {
	o.mock.ClearenvFunc = fn
}

func (o *mockOnCallOS) Environ(fn func() []string) {
	o.mock.EnvironFunc = fn
}

func (o *mockOnCallOS) ExpandEnv(fn func(s string) string) {
	o.mock.ExpandEnvFunc = fn
}

func (o *mockOnCallOS) Getenv(fn func(key string) string) {
	o.mock.GetenvFunc = fn
}

func (o *mockOnCallOS) LookupEnv(fn func(key string) (string, bool)) {
	o.mock.LookupEnvFunc = fn
}

func (o *mockOnCallOS) Setenv(fn func(key, value string) error) {
	o.mock.SetenvFunc = fn
}

func (o *mockOnCallOS) Unsetenv(fn func(key string) error) {
	o.mock.UnsetenvFunc = fn
}

func (o *mockOnCallOS) Getpid(fn func() int) {
	o.mock.GetpidFunc = fn
}

func (o *mockOnCallOS) Getppid(fn func() int) {
	o.mock.GetppidFunc = fn
}

func (o *mockOnCallOS) Getuid(fn func() int) {
	o.mock.GetuidFunc = fn
}

func (o *mockOnCallOS) Getgid(fn func() int) {
	o.mock.GetgidFunc = fn
}

func (o *mockOnCallOS) Geteuid(fn func() int) {
	o.mock.GeteuidFunc = fn
}

func (o *mockOnCallOS) Getegid(fn func() int) {
	o.mock.GetegidFunc = fn
}

func (o *mockOnCallOS) Getgroups(fn func() ([]int, error)) {
	o.mock.GetgroupsFunc = fn
}

func (o *mockOnCallOS) Hostname(fn func() (string, error)) {
	o.mock.HostnameFunc = fn
}

func (o *mockOnCallOS) Executable(fn func() (string, error)) {
	o.mock.ExecutableFunc = fn
}

func (o *mockOnCallOS) Exit(fn func(code int)) {
	o.mock.ExitFunc = fn
}

func (o *mockOnCallOS) Getwd(fn func() (string, error)) {
	o.mock.GetwdFunc = fn
}

func (o *mockOnCallOS) Chdir(fn func(dir string) error) {
	o.mock.ChdirFunc = fn
}

func (o *mockOnCallOS) ReadDir(fn func(name string) ([]fs.DirEntry, error)) {
	o.mock.ReadDirFunc = fn
}

type mockSetReturnOS struct {
	mock *MockOS
}

func (r *mockSetReturnOS) Create(result0 bfs.IFileBridge, err error) {
	r.mock.OnCall.Create(func(name string) (bfs.IFileBridge, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) Open(result0 bfs.IFileBridge, err error) {
	r.mock.OnCall.Open(func(name string) (bfs.IFileBridge, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) OpenFile(result0 bfs.IFileBridge, err error) {
	r.mock.OnCall.OpenFile(func(name string, flag int, perm os.FileMode) (bfs.IFileBridge, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) CreateTemp(result0 bfs.IFileBridge, err error) {
	r.mock.OnCall.CreateTemp(func(dir, pattern string) (bfs.IFileBridge, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) Mkdir(err error) {
	r.mock.OnCall.Mkdir(func(name string, perm os.FileMode) error {
		return err
	})
}

func (r *mockSetReturnOS) MkdirAll(err error) {
	r.mock.OnCall.MkdirAll(func(path string, perm os.FileMode) error {
		return err
	})
}

func (r *mockSetReturnOS) Remove(err error) {
	r.mock.OnCall.Remove(func(name string) error {
		return err
	})
}

func (r *mockSetReturnOS) RemoveAll(err error) {
	r.mock.OnCall.RemoveAll(func(path string) error {
		return err
	})
}

func (r *mockSetReturnOS) Rename(err error) {
	r.mock.OnCall.Rename(func(oldpath, newpath string) error {
		return err
	})
}

func (r *mockSetReturnOS) Symlink(err error) {
	r.mock.OnCall.Symlink(func(oldname, newname string) error {
		return err
	})
}

func (r *mockSetReturnOS) Readlink(result0 string, err error) {
	r.mock.OnCall.Readlink(func(name string) (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) Chmod(err error) {
	r.mock.OnCall.Chmod(func(name string, mode os.FileMode) error {
		return err
	})
}

func (r *mockSetReturnOS) Chown(err error) {
	r.mock.OnCall.Chown(func(name string, uid, gid int) error {
		return err
	})
}

func (r *mockSetReturnOS) Lchown(err error) {
	r.mock.OnCall.Lchown(func(name string, uid, gid int) error {
		return err
	})
}

func (r *mockSetReturnOS) Chtimes(err error) {
	r.mock.OnCall.Chtimes(func(name string, atime time.Time, mtime time.Time) error {
		return err
	})
}

func (r *mockSetReturnOS) Stat(result0 bfs.IFileInfoBridge, err error) {
	r.mock.OnCall.Stat(func(name string) (bfs.IFileInfoBridge, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) Lstat(result0 bfs.IFileInfoBridge, err error) {
	r.mock.OnCall.Lstat(func(name string) (bfs.IFileInfoBridge, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) IsNotExist(result bool) {
	r.mock.OnCall.IsNotExist(func(err error) bool {
		return result
	})
}

func (r *mockSetReturnOS) IsExist(result bool) {
	r.mock.OnCall.IsExist(func(err error) bool {
		return result
	})
}

func (r *mockSetReturnOS) IsPermission(result bool) {
	r.mock.OnCall.IsPermission(func(err error) bool {
		return result
	})
}

func (r *mockSetReturnOS) UserCacheDir(result0 string, err error) {
	r.mock.OnCall.UserCacheDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) UserConfigDir(result0 string, err error) {
	r.mock.OnCall.UserConfigDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) UserHomeDir(result0 string, err error) {
	r.mock.OnCall.UserHomeDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) UserLogDir(result0 string, err error) {
	r.mock.OnCall.UserLogDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) TempDir(result string) {
	r.mock.OnCall.TempDir(func() string {
		return result
	})
}

func (r *mockSetReturnOS) Clearenv() {
	r.mock.OnCall.Clearenv(func() {
	})
}

func (r *mockSetReturnOS) Environ(result []string) {
	r.mock.OnCall.Environ(func() []string {
		return result
	})
}

func (r *mockSetReturnOS) ExpandEnv(result string) {
	r.mock.OnCall.ExpandEnv(func(s string) string {
		return result
	})
}

func (r *mockSetReturnOS) Getenv(result string) {
	r.mock.OnCall.Getenv(func(key string) string {
		return result
	})
}

func (r *mockSetReturnOS) LookupEnv(result0 string, result1 bool) {
	r.mock.OnCall.LookupEnv(func(key string) (string, bool) {
		return result0, result1
	})
}

func (r *mockSetReturnOS) Setenv(err error) {
	r.mock.OnCall.Setenv(func(key, value string) error {
		return err
	})
}

func (r *mockSetReturnOS) Unsetenv(err error) {
	r.mock.OnCall.Unsetenv(func(key string) error {
		return err
	})
}

func (r *mockSetReturnOS) Getpid(result int) {
	r.mock.OnCall.Getpid(func() int {
		return result
	})
}

func (r *mockSetReturnOS) Getppid(result int) {
	r.mock.OnCall.Getppid(func() int {
		return result
	})
}

func (r *mockSetReturnOS) Getuid(result int) {
	r.mock.OnCall.Getuid(func() int {
		return result
	})
}

func (r *mockSetReturnOS) Getgid(result int) {
	r.mock.OnCall.Getgid(func() int {
		return result
	})
}

func (r *mockSetReturnOS) Geteuid(result int) {
	r.mock.OnCall.Geteuid(func() int {
		return result
	})
}

func (r *mockSetReturnOS) Getegid(result int) {
	r.mock.OnCall.Getegid(func() int {
		return result
	})
}

func (r *mockSetReturnOS) Getgroups(result0 []int, err error) {
	r.mock.OnCall.Getgroups(func() ([]int, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) Hostname(result0 string, err error) {
	r.mock.OnCall.Hostname(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) Executable(result0 string, err error) {
	r.mock.OnCall.Executable(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) Exit() {
	r.mock.OnCall.Exit(func(code int) {
	})
}

func (r *mockSetReturnOS) Getwd(result0 string, err error) {
	r.mock.OnCall.Getwd(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnOS) Chdir(err error) {
	r.mock.OnCall.Chdir(func(dir string) error {
		return err
	})
}

func (r *mockSetReturnOS) ReadDir(result0 []fs.DirEntry, err error) {
	r.mock.OnCall.ReadDir(func(name string) ([]fs.DirEntry, error) {
		return result0, err
	})
}
