// Code generated by xmocks; DO NOT EDIT.
package pkgxmock

import (
	"fmt"
	"io/fs"
	"os"
	"runtime"
)

type TestCaseXFS struct {
	Name        string
	Env         map[string]string
	Input       any
	Want        any
	WantErr     bool
	ErrContains string
	MockFn      func(m *MockXFS)
}

func NewMockXFS() *MockXFS {
	mock := &MockXFS{}
	mock.OnCall = &mockOnCallXFS{mock: mock}
	mock.SetReturn = &mockSetReturnXFS{mock: mock}
	return mock
}

type MockXFS struct {
	FilepathAbsFunc        func(path string) (string, error)
	RetrieveFullPathFunc   func(path string) (string, error)
	GetUserHomeDirFunc     func() (string, error)
	GetUserConfigDirFunc   func() (string, error)
	GetUserDataDirFunc     func(appName string) (string, error)
	GetUserLogDirFunc      func(appName string) (string, error)
	GetParentPathFunc      func(filePath string) (string, error)
	ReadDirFunc            func(f *os.File, n int) ([]fs.DirEntry, error)
	IsDirFunc              func(path string) bool
	ExistsFunc             func(path string) bool
	OsStatFunc             func(name string) (os.FileInfo, error)
	OsOpenFunc             func(name string) (*os.File, error)
	OSUserDataDirFunc      func(home string, appName string) string
	OSUserLogDirFunc       func(home string, appName string) string
	OsOpenFileFunc         func(name string, flag int, perm os.FileMode) (*os.File, error)
	OsCreateTempFunc       func(dir, pattern string) (*os.File, error)
	OsRemoveFunc           func(name string) error
	OsRemoveAllFunc        func(path string) error
	OsChmodFunc            func(name string, mode os.FileMode) error
	OsMkdirFunc            func(name string, perm os.FileMode) error
	OsMkdirAllFunc         func(path string, perm os.FileMode) error
	GetVolumeFreeSpaceFunc func(currentPath string, requiredBytes uint64) (bool, error)
	GetRuntimeGOOSFunc     func() string
	OnCall                 *mockOnCallXFS
	SetReturn              *mockSetReturnXFS
}

func (m *MockXFS) panicIfNotConfigured() {
	pc, _, _, ok := runtime.Caller(2)
	methodName := "UnknownMethod"
	if ok {
		fullFnName := runtime.FuncForPC(pc).Name()
		shortName := fullFnName
		for i := len(fullFnName) - 1; i >= 0; i-- {
			if fullFnName[i] == '/' {
				shortName = fullFnName[i+1:]
				break
			}
		}
		methodName = shortName
	}
	panic(fmt.Sprintf("CRITICAL: Mock for %s not configured.", methodName))
}

func (m *MockXFS) FilepathAbs(path string) (string, error) {
	if m.FilepathAbsFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.FilepathAbsFunc(path)
}

func (m *MockXFS) RetrieveFullPath(path string) (string, error) {
	if m.RetrieveFullPathFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.RetrieveFullPathFunc(path)
}

func (m *MockXFS) GetUserHomeDir() (string, error) {
	if m.GetUserHomeDirFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.GetUserHomeDirFunc()
}

func (m *MockXFS) GetUserConfigDir() (string, error) {
	if m.GetUserConfigDirFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.GetUserConfigDirFunc()
}

func (m *MockXFS) GetUserDataDir(appName string) (string, error) {
	if m.GetUserDataDirFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.GetUserDataDirFunc(appName)
}

func (m *MockXFS) GetUserLogDir(appName string) (string, error) {
	if m.GetUserLogDirFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.GetUserLogDirFunc(appName)
}

func (m *MockXFS) GetParentPath(filePath string) (string, error) {
	if m.GetParentPathFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.GetParentPathFunc(filePath)
}

func (m *MockXFS) ReadDir(f *os.File, n int) ([]fs.DirEntry, error) {
	if m.ReadDirFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.ReadDirFunc(f, n)
}

func (m *MockXFS) IsDir(path string) bool {
	if m.IsDirFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.IsDirFunc(path)
}

func (m *MockXFS) Exists(path string) bool {
	if m.ExistsFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.ExistsFunc(path)
}

func (m *MockXFS) OsStat(name string) (os.FileInfo, error) {
	if m.OsStatFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.OsStatFunc(name)
}

func (m *MockXFS) OsOpen(name string) (*os.File, error) {
	if m.OsOpenFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.OsOpenFunc(name)
}

func (m *MockXFS) OSUserDataDir(home string, appName string) string {
	if m.OSUserDataDirFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.OSUserDataDirFunc(home, appName)
}

func (m *MockXFS) OSUserLogDir(home string, appName string) string {
	if m.OSUserLogDirFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.OSUserLogDirFunc(home, appName)
}

func (m *MockXFS) OsOpenFile(name string, flag int, perm os.FileMode) (*os.File, error) {
	if m.OsOpenFileFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.OsOpenFileFunc(name, flag, perm)
}

func (m *MockXFS) OsCreateTemp(dir, pattern string) (*os.File, error) {
	if m.OsCreateTempFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.OsCreateTempFunc(dir, pattern)
}

func (m *MockXFS) OsRemove(name string) error {
	if m.OsRemoveFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.OsRemoveFunc(name)
}

func (m *MockXFS) OsRemoveAll(path string) error {
	if m.OsRemoveAllFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.OsRemoveAllFunc(path)
}

func (m *MockXFS) OsChmod(name string, mode os.FileMode) error {
	if m.OsChmodFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.OsChmodFunc(name, mode)
}

func (m *MockXFS) OsMkdir(name string, perm os.FileMode) error {
	if m.OsMkdirFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.OsMkdirFunc(name, perm)
}

func (m *MockXFS) OsMkdirAll(path string, perm os.FileMode) error {
	if m.OsMkdirAllFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.OsMkdirAllFunc(path, perm)
}

func (m *MockXFS) GetVolumeFreeSpace(currentPath string, requiredBytes uint64) (bool, error) {
	if m.GetVolumeFreeSpaceFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.GetVolumeFreeSpaceFunc(currentPath, requiredBytes)
}

func (m *MockXFS) GetRuntimeGOOS() string {
	if m.GetRuntimeGOOSFunc == nil {
		m.panicIfNotConfigured()
	}
	return m.GetRuntimeGOOSFunc()
}

type mockOnCallXFS struct {
	mock *MockXFS
}

func (o *mockOnCallXFS) FilepathAbs(fn func(path string) (string, error)) {
	o.mock.FilepathAbsFunc = fn
}

func (o *mockOnCallXFS) RetrieveFullPath(fn func(path string) (string, error)) {
	o.mock.RetrieveFullPathFunc = fn
}

func (o *mockOnCallXFS) GetUserHomeDir(fn func() (string, error)) {
	o.mock.GetUserHomeDirFunc = fn
}

func (o *mockOnCallXFS) GetUserConfigDir(fn func() (string, error)) {
	o.mock.GetUserConfigDirFunc = fn
}

func (o *mockOnCallXFS) GetUserDataDir(fn func(appName string) (string, error)) {
	o.mock.GetUserDataDirFunc = fn
}

func (o *mockOnCallXFS) GetUserLogDir(fn func(appName string) (string, error)) {
	o.mock.GetUserLogDirFunc = fn
}

func (o *mockOnCallXFS) GetParentPath(fn func(filePath string) (string, error)) {
	o.mock.GetParentPathFunc = fn
}

func (o *mockOnCallXFS) ReadDir(fn func(f *os.File, n int) ([]fs.DirEntry, error)) {
	o.mock.ReadDirFunc = fn
}

func (o *mockOnCallXFS) IsDir(fn func(path string) bool) {
	o.mock.IsDirFunc = fn
}

func (o *mockOnCallXFS) Exists(fn func(path string) bool) {
	o.mock.ExistsFunc = fn
}

func (o *mockOnCallXFS) OsStat(fn func(name string) (os.FileInfo, error)) {
	o.mock.OsStatFunc = fn
}

func (o *mockOnCallXFS) OsOpen(fn func(name string) (*os.File, error)) {
	o.mock.OsOpenFunc = fn
}

func (o *mockOnCallXFS) OSUserDataDir(fn func(home string, appName string) string) {
	o.mock.OSUserDataDirFunc = fn
}

func (o *mockOnCallXFS) OSUserLogDir(fn func(home string, appName string) string) {
	o.mock.OSUserLogDirFunc = fn
}

func (o *mockOnCallXFS) OsOpenFile(fn func(name string, flag int, perm os.FileMode) (*os.File, error)) {
	o.mock.OsOpenFileFunc = fn
}

func (o *mockOnCallXFS) OsCreateTemp(fn func(dir, pattern string) (*os.File, error)) {
	o.mock.OsCreateTempFunc = fn
}

func (o *mockOnCallXFS) OsRemove(fn func(name string) error) {
	o.mock.OsRemoveFunc = fn
}

func (o *mockOnCallXFS) OsRemoveAll(fn func(path string) error) {
	o.mock.OsRemoveAllFunc = fn
}

func (o *mockOnCallXFS) OsChmod(fn func(name string, mode os.FileMode) error) {
	o.mock.OsChmodFunc = fn
}

func (o *mockOnCallXFS) OsMkdir(fn func(name string, perm os.FileMode) error) {
	o.mock.OsMkdirFunc = fn
}

func (o *mockOnCallXFS) OsMkdirAll(fn func(path string, perm os.FileMode) error) {
	o.mock.OsMkdirAllFunc = fn
}

func (o *mockOnCallXFS) GetVolumeFreeSpace(fn func(currentPath string, requiredBytes uint64) (bool, error)) {
	o.mock.GetVolumeFreeSpaceFunc = fn
}

func (o *mockOnCallXFS) GetRuntimeGOOS(fn func() string) {
	o.mock.GetRuntimeGOOSFunc = fn
}

type mockSetReturnXFS struct {
	mock *MockXFS
}

func (r *mockSetReturnXFS) FilepathAbs(result0 string, err error) {
	r.mock.OnCall.FilepathAbs(func(path string) (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) RetrieveFullPath(result0 string, err error) {
	r.mock.OnCall.RetrieveFullPath(func(path string) (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetUserHomeDir(result0 string, err error) {
	r.mock.OnCall.GetUserHomeDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetUserConfigDir(result0 string, err error) {
	r.mock.OnCall.GetUserConfigDir(func() (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetUserDataDir(result0 string, err error) {
	r.mock.OnCall.GetUserDataDir(func(appName string) (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetUserLogDir(result0 string, err error) {
	r.mock.OnCall.GetUserLogDir(func(appName string) (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetParentPath(result0 string, err error) {
	r.mock.OnCall.GetParentPath(func(filePath string) (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) ReadDir(result0 []fs.DirEntry, err error) {
	r.mock.OnCall.ReadDir(func(f *os.File, n int) ([]fs.DirEntry, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) IsDir(result bool) {
	r.mock.OnCall.IsDir(func(path string) bool {
		return result
	})
}

func (r *mockSetReturnXFS) Exists(result bool) {
	r.mock.OnCall.Exists(func(path string) bool {
		return result
	})
}

func (r *mockSetReturnXFS) OsStat(result0 os.FileInfo, err error) {
	r.mock.OnCall.OsStat(func(name string) (os.FileInfo, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) OsOpen(result0 *os.File, err error) {
	r.mock.OnCall.OsOpen(func(name string) (*os.File, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) OSUserDataDir(result string) {
	r.mock.OnCall.OSUserDataDir(func(home string, appName string) string {
		return result
	})
}

func (r *mockSetReturnXFS) OSUserLogDir(result string) {
	r.mock.OnCall.OSUserLogDir(func(home string, appName string) string {
		return result
	})
}

func (r *mockSetReturnXFS) OsOpenFile(result0 *os.File, err error) {
	r.mock.OnCall.OsOpenFile(func(name string, flag int, perm os.FileMode) (*os.File, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) OsCreateTemp(result0 *os.File, err error) {
	r.mock.OnCall.OsCreateTemp(func(dir, pattern string) (*os.File, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) OsRemove(err error) {
	r.mock.OnCall.OsRemove(func(name string) error {
		return err
	})
}

func (r *mockSetReturnXFS) OsRemoveAll(err error) {
	r.mock.OnCall.OsRemoveAll(func(path string) error {
		return err
	})
}

func (r *mockSetReturnXFS) OsChmod(err error) {
	r.mock.OnCall.OsChmod(func(name string, mode os.FileMode) error {
		return err
	})
}

func (r *mockSetReturnXFS) OsMkdir(err error) {
	r.mock.OnCall.OsMkdir(func(name string, perm os.FileMode) error {
		return err
	})
}

func (r *mockSetReturnXFS) OsMkdirAll(err error) {
	r.mock.OnCall.OsMkdirAll(func(path string, perm os.FileMode) error {
		return err
	})
}

func (r *mockSetReturnXFS) GetVolumeFreeSpace(result0 bool, err error) {
	r.mock.OnCall.GetVolumeFreeSpace(func(currentPath string, requiredBytes uint64) (bool, error) {
		return result0, err
	})
}

func (r *mockSetReturnXFS) GetRuntimeGOOS(result string) {
	r.mock.OnCall.GetRuntimeGOOS(func() string {
		return result
	})
}
