package bos

import (
	"io/fs"
	"os"
	"time"

	"github.com/AeonDigital/Go-Core/xbridge/go/bio/bfs"
)

// IOSBridge defines the unified contract to intercept and mock the Go standard library 'os' package.
// This interface decouples system level operations from the application domain, allowing safe unit testing.
type IOSBridge interface {
	// =========================================================================
	// FILE & DIRECTORY CRUD OPERATIONS
	// =========================================================================

	// Create creates or truncates the named file. If the file already exists,
	// it is truncated. If the file does not exist, it is created with mode 0o666
	// (before umask). If successful, methods on the returned File can
	// be used for I/O; the associated file descriptor has mode [O_RDWR].
	// The directory containing the file must already exist.
	// If there is an error, it will be of type [*PathError].
	Create(name string) (bfs.IFileBridge, error)
	// Open opens the named file for reading. If successful, methods on
	// the returned file can be used for reading; the associated file
	// descriptor has mode [O_RDONLY].
	// If there is an error, it will be of type [*PathError].
	Open(name string) (bfs.IFileBridge, error)
	// OpenFile is the generalized open call; most users will use Open
	// or Create instead. It opens the named file with specified flag
	// ([O_RDONLY] etc.). If the file does not exist, and the [O_CREATE] flag
	// is passed, it is created with mode perm (before umask);
	// the containing directory must exist. If successful,
	// methods on the returned File can be used for I/O.
	// If there is an error, it will be of type [*PathError].
	OpenFile(name string, flag int, perm os.FileMode) (bfs.IFileBridge, error)
	// CreateTemp creates a new temporary file in the directory dir,
	// opens the file for reading and writing, and returns the resulting file.
	// The filename is generated by taking pattern and adding a random string to the end.
	// If pattern includes a "*", the random string replaces the last "*".
	// The file is created with mode 0o600 (before umask).
	// If dir is the empty string, CreateTemp uses the default directory for temporary files, as returned by [TempDir].
	// Multiple programs or goroutines calling CreateTemp simultaneously will not choose the same file.
	// The caller can use the file's Name method to find the pathname of the file.
	// It is the caller's responsibility to remove the file when it is no longer needed.
	CreateTemp(dir, pattern string) (bfs.IFileBridge, error)
	// Mkdir creates a new directory with the specified name and permission
	// bits (before umask).
	// If there is an error, it will be of type [*PathError].
	Mkdir(name string, perm os.FileMode) error
	// MkdirAll creates a directory named path,
	// along with any necessary parents, and returns nil,
	// or else returns an error.
	// The permission bits perm (before umask) are used for all
	// directories that MkdirAll creates.
	// If path is already a directory, MkdirAll does nothing
	// and returns nil.
	MkdirAll(path string, perm os.FileMode) error
	// Remove removes the named file or (empty) directory.
	// If there is an error, it will be of type [*PathError].
	Remove(name string) error
	// RemoveAll removes path and any children it contains.
	// It removes everything it can but returns the first error
	// it encounters. If the path does not exist, RemoveAll
	// returns nil (no error).
	// If there is an error, it will be of type [*PathError].
	RemoveAll(path string) error
	// Rename renames (moves) oldpath to newpath.
	// If newpath already exists and is not a directory, Rename replaces it.
	// If newpath already exists and is a directory, Rename returns an error.
	// OS-specific restrictions may apply when oldpath and newpath are in different directories.
	// Even within the same directory, on non-Unix platforms Rename is not an atomic operation.
	// If there is an error, it will be of type *LinkError.
	Rename(oldpath, newpath string) error
	// Link creates newname as a hard link to the oldname file.
	// If there is an error, it will be of type *LinkError.	Link(oldname, newname string) error
	Symlink(oldname, newname string) error
	// Readlink returns the destination of the named symbolic link.
	// If there is an error, it will be of type [*PathError].
	//
	// If the link destination is relative, Readlink returns the relative path
	// without resolving it to an absolute one.
	Readlink(name string) (string, error)

	// =========================================================================
	// FILE METADATA & PERMISSIONS
	// =========================================================================

	// Chmod changes the mode of the named file to mode.
	// If the file is a symbolic link, it changes the mode of the link's target.
	// If there is an error, it will be of type [*PathError].
	//
	// A different subset of the mode bits are used, depending on the
	// operating system.
	//
	// On Unix, the mode's permission bits, [ModeSetuid], [ModeSetgid], and
	// [ModeSticky] are used.
	//
	// On Windows, only the 0o200 bit (owner writable) of mode is used; it
	// controls whether the file's read-only attribute is set or cleared.
	// The other bits are currently unused. For compatibility with Go 1.12
	// and earlier, use a non-zero mode. Use mode 0o400 for a read-only
	// file and 0o600 for a readable+writable file.
	//
	// On Plan 9, the mode's permission bits, [ModeAppend], [ModeExclusive],
	// and [ModeTemporary] are used.
	Chmod(name string, mode os.FileMode) error
	// Chown changes the numeric uid and gid of the named file.
	// If the file is a symbolic link, it changes the uid and gid of the link's target.
	// A uid or gid of -1 means to not change that value.
	// If there is an error, it will be of type [*PathError].
	//
	// On Windows or Plan 9, Chown always returns the [syscall.EWINDOWS] or
	// [syscall.EPLAN9] error, wrapped in [*PathError].
	Chown(name string, uid, gid int) error
	// Lchown changes the numeric uid and gid of the named file.
	// If the file is a symbolic link, it changes the uid and gid of the link itself.
	// If there is an error, it will be of type [*PathError].
	//
	// On Windows, it always returns the [syscall.EWINDOWS] error, wrapped
	// in [*PathError].
	Lchown(name string, uid, gid int) error
	// Chtimes changes the access and modification times of the named
	// file, similar to the Unix utime() or utimes() functions.
	// A zero [time.Time] value will leave the corresponding file time unchanged.
	//
	// The underlying filesystem may truncate or round the values to a
	// less precise time unit.
	// If there is an error, it will be of type [*PathError].
	Chtimes(name string, atime time.Time, mtime time.Time) error
	// Stat returns a [FileInfo] describing the named file.
	// If there is an error, it will be of type [*PathError].
	Stat(name string) (bfs.IFileInfoBridge, error)
	// Lstat returns a [FileInfo] describing the named file.
	// If the file is a symbolic link, the returned FileInfo
	// describes the symbolic link. Lstat makes no attempt to follow the link.
	// If there is an error, it will be of type [*PathError].
	//
	// On Windows, if the file is a reparse point that is a surrogate for another
	// named entity (such as a symbolic link or mounted folder), the returned
	// FileInfo describes the reparse point, and makes no attempt to resolve it.
	Lstat(name string) (bfs.IFileInfoBridge, error)
	// IsNotExist returns a boolean indicating whether its argument is known to
	// report that a file or directory does not exist. It is satisfied by
	// [ErrNotExist] as well as some syscall errors.
	//
	// This function predates [errors.Is]. It only supports errors returned by
	// the os package. New code should use errors.Is(err, fs.ErrNotExist).
	IsNotExist(err error) bool
	// IsExist returns a boolean indicating whether its argument is known to report
	// that a file or directory already exists. It is satisfied by [ErrExist] as
	// well as some syscall errors.
	//
	// This function predates [errors.Is]. It only supports errors returned by
	// the os package. New code should use errors.Is(err, fs.ErrExist).
	IsExist(err error) bool
	// IsPermission returns a boolean indicating whether its argument is known to
	// report that permission is denied. It is satisfied by [ErrPermission] as well
	// as some syscall errors.
	//
	// This function predates [errors.Is]. It only supports errors returned by
	// the os package. New code should use errors.Is(err, fs.ErrPermission).
	IsPermission(err error) bool

	// =========================================================================
	// SYSTEM DIRECTORIES
	// =========================================================================

	// UserCacheDir returns the default root directory to use for user-specific
	// cached data. Users should create their own application-specific subdirectory
	// within this one and use that.
	//
	// On Unix systems, it returns $XDG_CACHE_HOME as specified by
	// https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html if
	// non-empty, else $HOME/.cache.
	// On Darwin, it returns $HOME/Library/Caches.
	// On Windows, it returns %LocalAppData%.
	// On Plan 9, it returns $home/lib/cache.
	//
	// If the location cannot be determined (for example, $HOME is not defined) or
	// the path in $XDG_CACHE_HOME is relative, then it will return an error.
	UserCacheDir() (string, error)
	// UserConfigDir returns the default root directory to use for user-specific
	// configuration data. Users should create their own application-specific
	// subdirectory within this one and use that.
	//
	// On Unix systems, it returns $XDG_CONFIG_HOME as specified by
	// https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html if
	// non-empty, else $HOME/.config.
	// On Darwin, it returns $HOME/Library/Application Support.
	// On Windows, it returns %AppData%.
	// On Plan 9, it returns $home/lib.
	//
	// If the location cannot be determined (for example, $HOME is not defined) or
	// the path in $XDG_CONFIG_HOME is relative, then it will return an error.
	UserConfigDir() (string, error)
	// UserHomeDir returns the current user's home directory.
	//
	// On Unix, including macOS, it returns the $HOME environment variable.
	// On Windows, it returns %USERPROFILE%.
	// On Plan 9, it returns the $home environment variable.
	//
	// If the expected variable is not set in the environment, UserHomeDir
	// returns either a platform-specific default value or a non-nil error.
	UserHomeDir() (string, error)
	// UserLogDir returns the default root directory to use for user-specific
	// application log data. Users should create their own application-specific
	// subdirectory within this one and use that.
	//
	// On Windows, it returns %LocalAppData%\Logs if %LocalAppData% is set,
	// otherwise it falls back to $HOME\AppData\Local\Logs.
	// On Darwin, it returns $HOME/Library/Logs.
	// On other Unix systems, it returns $XDG_STATE_HOME if non-empty,
	// otherwise it falls back to $HOME/.local/state.
	//
	// If the location cannot be determined (for example, $HOME is not defined),
	// then it will return an error.
	UserLogDir() (string, error)
	// TempDir returns the default directory to use for temporary files.
	//
	// On Unix systems, it returns $TMPDIR if non-empty, else /tmp.
	// On Windows, it uses GetTempPath, returning the first non-empty
	// value from %TMP%, %TEMP%, %USERPROFILE%, or the Windows directory.
	// On Plan 9, it returns /tmp.
	//
	// The directory is neither guaranteed to exist nor have accessible
	// permissions.
	TempDir() string

	// =========================================================================
	// ENVIRONMENT VARIABLES
	// =========================================================================

	// Clearenv deletes all environment variables.
	Clearenv()
	// Environ returns a copy of strings representing the environment,
	// in the form "key=value".
	Environ() []string
	// ExpandEnv replaces ${var} or $var in the string according to the values
	// of the current environment variables. References to undefined
	// variables are replaced by the empty string.
	ExpandEnv(s string) string
	// Getenv retrieves the value of the environment variable named by the key.
	// It returns the value, which will be empty if the variable is not present.
	// To distinguish between an empty value and an unset value, use [LookupEnv].
	Getenv(key string) string
	// LookupEnv retrieves the value of the environment variable named
	// by the key. If the variable is present in the environment the
	// value (which may be empty) is returned and the boolean is true.
	// Otherwise the returned value will be empty and the boolean will
	// be false.
	LookupEnv(key string) (string, bool)
	// Setenv sets the value of the environment variable named by the key.
	// It returns an error, if any.
	Setenv(key, value string) error
	// Unsetenv unsets a single environment variable.
	Unsetenv(key string) error

	// =========================================================================
	// PROCESS & SYSTEM INFO
	// =========================================================================

	// Getpid returns the process id of the caller.
	Getpid() int
	// Getppid returns the process id of the caller's parent.
	Getppid() int
	// Getuid returns the numeric user id of the caller.
	//
	// On Windows, it returns -1.
	Getuid() int
	// Getgid returns the numeric group id of the caller.
	//
	// On Windows, it returns -1.
	Getgid() int
	// Geteuid returns the numeric effective user id of the caller.
	//
	// On Windows, it returns -1.
	Geteuid() int
	// Getegid returns the numeric effective group id of the caller.
	//
	// On Windows, it returns -1.
	Getegid() int
	// Getgroups returns a list of the numeric ids of groups that the caller belongs to.
	//
	// On Windows, it returns [syscall.EWINDOWS]. See the [os/user] package
	// for a possible alternative.
	Getgroups() ([]int, error)
	// Hostname returns the host name reported by the kernel.
	Hostname() (string, error)
	// Executable returns the path name for the executable that started
	// the current process. There is no guarantee that the path is still
	// pointing to the correct executable. If a symlink was used to start
	// the process, depending on the operating system, the result might
	// be the symlink or the path it pointed to. If a stable result is
	// needed, [path/filepath.EvalSymlinks] might help.
	//
	// Executable returns an absolute path unless an error occurred.
	//
	// The main use case is finding resources located relative to an
	// executable.
	Executable() (string, error)
	// Exit causes the current program to exit with the given status code.
	// Conventionally, code zero indicates success, non-zero an error.
	// The program terminates immediately; deferred functions are not run.
	//
	// For portability, the status code should be in the range [0, 125].
	Exit(code int)

	// =========================================================================
	// WORKING DIRECTORY
	// =========================================================================

	// Getwd returns an absolute path name corresponding to the
	// current directory. If the current directory can be
	// reached via multiple paths (due to symbolic links),
	// Getwd may return any one of them.
	//
	// On Unix platforms, if the environment variable PWD
	// provides an absolute name, and it is a name of the
	// current directory, it is returned.
	Getwd() (dir string, err error)
	// Chdir changes the current working directory to the named directory.
	// If there is an error, it will be of type [*PathError].
	Chdir(dir string) error

	// =========================================================================
	// DIRECTORY READING
	// =========================================================================

	// ReadDir reads the named directory,
	// returning all its directory entries sorted by filename.
	// If an error occurs reading the directory,
	// ReadDir returns the entries it was able to read before the error,
	// along with the error.
	ReadDir(name string) ([]fs.DirEntry, error)
}

// sosBridge serves as the private concrete production implementation of IOSBridge,
// routing calls natively to the standard library 'os' package.
type sosBridge struct{}

// Ensure at compile time that the private struct implements the public interface.
var _ IOSBridge = sosBridge{}

// NewOSBridge creates and returns a public, mockable IOSBridge instance pointing
// to the production operating system implementation.
func NewOS() IOSBridge {
	return sosBridge{}
}

// =========================================================================
// IMPLEMENTATION OF FILE & DIRECTORY CRUD OPERATIONS
// =========================================================================

func (sosBridge) Create(name string) (bfs.IFileBridge, error) {
	f, err := os.Create(name)
	if err != nil {
		return nil, err
	}
	return bfs.NewFile(f), nil
}
func (sosBridge) Open(name string) (bfs.IFileBridge, error) {
	f, err := os.Open(name)
	if err != nil {
		return nil, err
	}
	return bfs.NewFile(f), nil
}
func (sosBridge) OpenFile(name string, flag int, perm os.FileMode) (bfs.IFileBridge, error) {
	f, err := os.OpenFile(name, flag, perm)
	if err != nil {
		return nil, err
	}
	return bfs.NewFile(f), nil
}
func (sosBridge) CreateTemp(dir, pattern string) (bfs.IFileBridge, error) {
	f, err := os.CreateTemp(dir, pattern)
	if err != nil {
		return nil, err
	}
	return bfs.NewFile(f), nil
}
func (sosBridge) Mkdir(name string, perm os.FileMode) error    { return os.Mkdir(name, perm) }
func (sosBridge) MkdirAll(path string, perm os.FileMode) error { return os.MkdirAll(path, perm) }
func (sosBridge) Remove(name string) error                     { return os.Remove(name) }
func (sosBridge) RemoveAll(path string) error                  { return os.RemoveAll(path) }
func (sosBridge) Rename(oldpath, newpath string) error         { return os.Rename(oldpath, newpath) }
func (sosBridge) Link(oldname, newname string) error           { return os.Link(oldname, newname) }
func (sosBridge) Symlink(oldname, newname string) error {
	return os.Symlink(oldname, newname)
}
func (sosBridge) Readlink(name string) (string, error) { return os.Readlink(name) }

// =========================================================================
// IMPLEMENTATION OF FILE METADATA & PERMISSIONS
// =========================================================================

func (sosBridge) Chmod(name string, mode os.FileMode) error { return os.Chmod(name, mode) }
func (sosBridge) Chown(name string, uid, gid int) error     { return os.Chown(name, uid, gid) }
func (sosBridge) Lchown(name string, uid, gid int) error    { return os.Lchown(name, uid, gid) }
func (sosBridge) Chtimes(name string, atime time.Time, mtime time.Time) error {
	return os.Chtimes(name, atime, mtime)
}
func (sosBridge) Stat(name string) (bfs.IFileInfoBridge, error) {
	fi, err := os.Stat(name)
	if err != nil {
		return nil, err
	}
	return bfs.NewFileInfo(fi), nil
}
func (sosBridge) Lstat(name string) (bfs.IFileInfoBridge, error) {
	fi, err := os.Lstat(name)
	if err != nil {
		return nil, err
	}
	return bfs.NewFileInfo(fi), nil
}
func (sosBridge) IsNotExist(err error) bool   { return os.IsNotExist(err) }
func (sosBridge) IsExist(err error) bool      { return os.IsExist(err) }
func (sosBridge) IsPermission(err error) bool { return os.IsPermission(err) }

// =========================================================================
// IMPLEMENTATION OF SYSTEM DIRECTORIES
// =========================================================================

func (sosBridge) UserCacheDir() (string, error)  { return os.UserCacheDir() }
func (sosBridge) UserConfigDir() (string, error) { return os.UserConfigDir() }
func (sosBridge) UserHomeDir() (string, error)   { return os.UserHomeDir() }
func (sosBridge) UserLogDir() (string, error)    { return os_UserLogDir() }
func (sosBridge) TempDir() string                { return os.TempDir() }

// =========================================================================
// IMPLEMENTATION OF ENVIRONMENT VARIABLES
// =========================================================================

func (sosBridge) Clearenv()                 { os.Clearenv() }
func (sosBridge) Environ() []string         { return os.Environ() }
func (sosBridge) ExpandEnv(s string) string { return os.ExpandEnv(s) }
func (sosBridge) Getenv(key string) string  { return os.Getenv(key) }
func (sosBridge) LookupEnv(key string) (string, bool) {
	return os.LookupEnv(key)
}
func (sosBridge) Setenv(key, value string) error { return os.Setenv(key, value) }
func (sosBridge) Unsetenv(key string) error      { return os.Unsetenv(key) }

// =========================================================================
// IMPLEMENTATION OF PROCESS & SYSTEM INFO
// =========================================================================

func (sosBridge) Getpid() int                 { return os.Getpid() }
func (sosBridge) Getppid() int                { return os.Getppid() }
func (sosBridge) Getuid() int                 { return os.Getuid() }
func (sosBridge) Getgid() int                 { return os.Getgid() }
func (sosBridge) Geteuid() int                { return os.Geteuid() }
func (sosBridge) Getegid() int                { return os.Getegid() }
func (sosBridge) Getgroups() ([]int, error)   { return os.Getgroups() }
func (sosBridge) Hostname() (string, error)   { return os.Hostname() }
func (sosBridge) Executable() (string, error) { return os.Executable() }
func (sosBridge) Exit(code int)               { os.Exit(code) }

// =========================================================================
// IMPLEMENTATION OF WORKING DIRECTORY
// =========================================================================

func (sosBridge) Getwd() (dir string, err error) { return os.Getwd() }
func (sosBridge) Chdir(dir string) error         { return os.Chdir(dir) }

// =========================================================================
// IMPLEMENTATION OF DIRECTORY READING
// =========================================================================

func (sosBridge) ReadDir(name string) ([]fs.DirEntry, error) { return os.ReadDir(name) }

// =========================================================================
// GLOBAL PUBLIC INTERFACE INSTANCE
// =========================================================================

// OS is the global public variable used by all core application code
// to perform operating system file, directory, environment and process mechanics.
// It can be easily hot-swapped at unit test boundaries via generated pkgxmock utilities.
var OS IOSBridge = NewOS()
