// Code generated by xmocks; DO NOT EDIT.
package mocks

import (
	"fmt"
	"github.com/AeonDigital/Go-Core/xbridge/go/bio/bfs"
	"io/fs"
	"runtime"
)

type TestCaseFile struct {
	Name        string
	Env         map[string]string
	Input       any
	Want        any
	WantErr     bool
	ErrContains string
	MockFn      func(m *MockFile)
}

func NewMockFile() *MockFile {
	mock := &MockFile{}
	mock.OnCall = &mockOnCallFile{mock: mock}
	mock.SetReturn = &mockSetReturnFile{mock: mock}
	return mock
}

type MockFile struct {
	ReadFunc        func(b []byte) (int, error)
	ReadAtFunc      func(b []byte, off int64) (int, error)
	WriteFunc       func(b []byte) (int, error)
	WriteAtFunc     func(b []byte, off int64) (int, error)
	WriteStringFunc func(s string) (int, error)
	SeekFunc        func(offset int64, whence int) (int64, error)
	CloseFunc       func() error
	SyncFunc        func() error
	StatFunc        func() (bfs.IFileInfoBridge, error)
	FdFunc          func() uintptr
	NameFunc        func() string
	ReadDirFunc     func(n int) ([]fs.DirEntry, error)
	OnCall          *mockOnCallFile
	SetReturn       *mockSetReturnFile
}

func (m *MockFile) panicIfNotConfigured() {
	pc, _, _, ok := runtime.Caller(2)
	methodName := "UnknownMethod"
	if ok {
		fullFnName := runtime.FuncForPC(pc).Name()
		shortName := fullFnName
		for i := len(fullFnName) - 1; i >= 0; i-- {
			if fullFnName[i] == '/' {
				shortName = fullFnName[i+1:]
				break
			}
		}
		methodName = shortName
	}
	panic(fmt.Sprintf("CRITICAL: Mock for %s not configured.", methodName))
}

func (oMock *MockFile) Read(b []byte) (int, error) {
	if oMock.ReadFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ReadFunc(b)
}

func (oMock *MockFile) ReadAt(b []byte, off int64) (int, error) {
	if oMock.ReadAtFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ReadAtFunc(b, off)
}

func (oMock *MockFile) Write(b []byte) (int, error) {
	if oMock.WriteFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.WriteFunc(b)
}

func (oMock *MockFile) WriteAt(b []byte, off int64) (int, error) {
	if oMock.WriteAtFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.WriteAtFunc(b, off)
}

func (oMock *MockFile) WriteString(s string) (int, error) {
	if oMock.WriteStringFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.WriteStringFunc(s)
}

func (oMock *MockFile) Seek(offset int64, whence int) (int64, error) {
	if oMock.SeekFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.SeekFunc(offset, whence)
}

func (oMock *MockFile) Close() error {
	if oMock.CloseFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.CloseFunc()
}

func (oMock *MockFile) Sync() error {
	if oMock.SyncFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.SyncFunc()
}

func (oMock *MockFile) Stat() (bfs.IFileInfoBridge, error) {
	if oMock.StatFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.StatFunc()
}

func (oMock *MockFile) Fd() uintptr {
	if oMock.FdFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.FdFunc()
}

func (oMock *MockFile) Name() string {
	if oMock.NameFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.NameFunc()
}

func (oMock *MockFile) ReadDir(n int) ([]fs.DirEntry, error) {
	if oMock.ReadDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ReadDirFunc(n)
}

type mockOnCallFile struct {
	mock *MockFile
}

func (o *mockOnCallFile) Read(fn func(b []byte) (int, error)) {
	o.mock.ReadFunc = fn
}

func (o *mockOnCallFile) ReadAt(fn func(b []byte, off int64) (int, error)) {
	o.mock.ReadAtFunc = fn
}

func (o *mockOnCallFile) Write(fn func(b []byte) (int, error)) {
	o.mock.WriteFunc = fn
}

func (o *mockOnCallFile) WriteAt(fn func(b []byte, off int64) (int, error)) {
	o.mock.WriteAtFunc = fn
}

func (o *mockOnCallFile) WriteString(fn func(s string) (int, error)) {
	o.mock.WriteStringFunc = fn
}

func (o *mockOnCallFile) Seek(fn func(offset int64, whence int) (int64, error)) {
	o.mock.SeekFunc = fn
}

func (o *mockOnCallFile) Close(fn func() error) {
	o.mock.CloseFunc = fn
}

func (o *mockOnCallFile) Sync(fn func() error) {
	o.mock.SyncFunc = fn
}

func (o *mockOnCallFile) Stat(fn func() (bfs.IFileInfoBridge, error)) {
	o.mock.StatFunc = fn
}

func (o *mockOnCallFile) Fd(fn func() uintptr) {
	o.mock.FdFunc = fn
}

func (o *mockOnCallFile) Name(fn func() string) {
	o.mock.NameFunc = fn
}

func (o *mockOnCallFile) ReadDir(fn func(n int) ([]fs.DirEntry, error)) {
	o.mock.ReadDirFunc = fn
}

type mockSetReturnFile struct {
	mock *MockFile
}

func (r *mockSetReturnFile) Read(result0 int, err error) {
	r.mock.OnCall.Read(func(b []byte) (int, error) {
		return result0, err
	})
}

func (r *mockSetReturnFile) ReadAt(result0 int, err error) {
	r.mock.OnCall.ReadAt(func(b []byte, off int64) (int, error) {
		return result0, err
	})
}

func (r *mockSetReturnFile) Write(result0 int, err error) {
	r.mock.OnCall.Write(func(b []byte) (int, error) {
		return result0, err
	})
}

func (r *mockSetReturnFile) WriteAt(result0 int, err error) {
	r.mock.OnCall.WriteAt(func(b []byte, off int64) (int, error) {
		return result0, err
	})
}

func (r *mockSetReturnFile) WriteString(result0 int, err error) {
	r.mock.OnCall.WriteString(func(s string) (int, error) {
		return result0, err
	})
}

func (r *mockSetReturnFile) Seek(result0 int64, err error) {
	r.mock.OnCall.Seek(func(offset int64, whence int) (int64, error) {
		return result0, err
	})
}

func (r *mockSetReturnFile) Close(err error) {
	r.mock.OnCall.Close(func() error {
		return err
	})
}

func (r *mockSetReturnFile) Sync(err error) {
	r.mock.OnCall.Sync(func() error {
		return err
	})
}

func (r *mockSetReturnFile) Stat(result0 bfs.IFileInfoBridge, err error) {
	r.mock.OnCall.Stat(func() (bfs.IFileInfoBridge, error) {
		return result0, err
	})
}

func (r *mockSetReturnFile) Fd(result uintptr) {
	r.mock.OnCall.Fd(func() uintptr {
		return result
	})
}

func (r *mockSetReturnFile) Name(result string) {
	r.mock.OnCall.Name(func() string {
		return result
	})
}

func (r *mockSetReturnFile) ReadDir(result0 []fs.DirEntry, err error) {
	r.mock.OnCall.ReadDir(func(n int) ([]fs.DirEntry, error) {
		return result0, err
	})
}
