// Code generated by xmocks; DO NOT EDIT.
package mocks

import (
	"fmt"
	"os"
	"runtime"
	"time"
)

type TestCaseFileInfo struct {
	Name        string
	Env         map[string]string
	Input       any
	Want        any
	WantErr     bool
	ErrContains string
	MockFn      func(m *MockFileInfo)
}

func NewMockFileInfo() *MockFileInfo {
	mock := &MockFileInfo{}
	mock.OnCall = &mockOnCallFileInfo{mock: mock}
	mock.SetReturn = &mockSetReturnFileInfo{mock: mock}
	return mock
}

type MockFileInfo struct {
	NameFunc    func() string
	SizeFunc    func() int64
	ModeFunc    func() os.FileMode
	ModTimeFunc func() time.Time
	IsDirFunc   func() bool
	SysFunc     func() any
	OnCall      *mockOnCallFileInfo
	SetReturn   *mockSetReturnFileInfo
}

func (m *MockFileInfo) panicIfNotConfigured() {
	pc, _, _, ok := runtime.Caller(2)
	methodName := "UnknownMethod"
	if ok {
		fullFnName := runtime.FuncForPC(pc).Name()
		shortName := fullFnName
		for i := len(fullFnName) - 1; i >= 0; i-- {
			if fullFnName[i] == '/' {
				shortName = fullFnName[i+1:]
				break
			}
		}
		methodName = shortName
	}
	panic(fmt.Sprintf("CRITICAL: Mock for %s not configured.", methodName))
}

func (oMock *MockFileInfo) Name() string {
	if oMock.NameFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.NameFunc()
}

func (oMock *MockFileInfo) Size() int64 {
	if oMock.SizeFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.SizeFunc()
}

func (oMock *MockFileInfo) Mode() os.FileMode {
	if oMock.ModeFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ModeFunc()
}

func (oMock *MockFileInfo) ModTime() time.Time {
	if oMock.ModTimeFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ModTimeFunc()
}

func (oMock *MockFileInfo) IsDir() bool {
	if oMock.IsDirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.IsDirFunc()
}

func (oMock *MockFileInfo) Sys() any {
	if oMock.SysFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.SysFunc()
}

type mockOnCallFileInfo struct {
	mock *MockFileInfo
}

func (o *mockOnCallFileInfo) Name(fn func() string) {
	o.mock.NameFunc = fn
}

func (o *mockOnCallFileInfo) Size(fn func() int64) {
	o.mock.SizeFunc = fn
}

func (o *mockOnCallFileInfo) Mode(fn func() os.FileMode) {
	o.mock.ModeFunc = fn
}

func (o *mockOnCallFileInfo) ModTime(fn func() time.Time) {
	o.mock.ModTimeFunc = fn
}

func (o *mockOnCallFileInfo) IsDir(fn func() bool) {
	o.mock.IsDirFunc = fn
}

func (o *mockOnCallFileInfo) Sys(fn func() any) {
	o.mock.SysFunc = fn
}

type mockSetReturnFileInfo struct {
	mock *MockFileInfo
}

func (r *mockSetReturnFileInfo) Name(result string) {
	r.mock.OnCall.Name(func() string {
		return result
	})
}

func (r *mockSetReturnFileInfo) Size(result int64) {
	r.mock.OnCall.Size(func() int64 {
		return result
	})
}

func (r *mockSetReturnFileInfo) Mode(result os.FileMode) {
	r.mock.OnCall.Mode(func() os.FileMode {
		return result
	})
}

func (r *mockSetReturnFileInfo) ModTime(result time.Time) {
	r.mock.OnCall.ModTime(func() time.Time {
		return result
	})
}

func (r *mockSetReturnFileInfo) IsDir(result bool) {
	r.mock.OnCall.IsDir(func() bool {
		return result
	})
}

func (r *mockSetReturnFileInfo) Sys(result any) {
	r.mock.OnCall.Sys(func() any {
		return result
	})
}
