// Code generated by xmocks; DO NOT EDIT.
package mocks

import (
	"fmt"
	"runtime"
)

type TestCaseFilepath struct {
	Name        string
	Env         map[string]string
	Input       any
	Want        any
	WantErr     bool
	ErrContains string
	MockFn      func(m *MockFilepath)
}

func NewMockFilepath() *MockFilepath {
	mock := &MockFilepath{}
	mock.OnCall = &mockOnCallFilepath{mock: mock}
	mock.SetReturn = &mockSetReturnFilepath{mock: mock}
	return mock
}

type MockFilepath struct {
	AbsFunc           func(path string) (string, error)
	CleanFunc         func(path string) string
	DirFunc           func(path string) string
	BaseFunc          func(path string) string
	ExtFunc           func(path string) string
	FromSlashFunc     func(path string) string
	ToSlashFunc       func(path string) string
	JoinFunc          func(elem ...string) string
	SplitFunc         func(path string) string
	SplitListFunc     func(path string) []string
	EvalSymlinksFunc  func(path string) (string, error)
	GlobFunc          func(pattern string) ([]string, error)
	MatchFunc         func(pattern, name string) (bool, error)
	RelFunc           func(basepath, targpath string) (string, error)
	IsAbsFunc         func(path string) bool
	HasPrefixFunc     func(p, prefix string) bool
	IsInDirectoryFunc func(baseDir, targetPath string) bool
	VolumeNameFunc    func(path string) string
	OnCall            *mockOnCallFilepath
	SetReturn         *mockSetReturnFilepath
}

func (m *MockFilepath) panicIfNotConfigured() {
	pc, _, _, ok := runtime.Caller(2)
	methodName := "UnknownMethod"
	if ok {
		fullFnName := runtime.FuncForPC(pc).Name()
		shortName := fullFnName
		for i := len(fullFnName) - 1; i >= 0; i-- {
			if fullFnName[i] == '/' {
				shortName = fullFnName[i+1:]
				break
			}
		}
		methodName = shortName
	}
	panic(fmt.Sprintf("CRITICAL: Mock for %s not configured.", methodName))
}

func (oMock *MockFilepath) Abs(path string) (string, error) {
	if oMock.AbsFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.AbsFunc(path)
}

func (oMock *MockFilepath) Clean(path string) string {
	if oMock.CleanFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.CleanFunc(path)
}

func (oMock *MockFilepath) Dir(path string) string {
	if oMock.DirFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.DirFunc(path)
}

func (oMock *MockFilepath) Base(path string) string {
	if oMock.BaseFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.BaseFunc(path)
}

func (oMock *MockFilepath) Ext(path string) string {
	if oMock.ExtFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ExtFunc(path)
}

func (oMock *MockFilepath) FromSlash(path string) string {
	if oMock.FromSlashFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.FromSlashFunc(path)
}

func (oMock *MockFilepath) ToSlash(path string) string {
	if oMock.ToSlashFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ToSlashFunc(path)
}

func (oMock *MockFilepath) Join(elem ...string) string {
	if oMock.JoinFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.JoinFunc(elem...)
}

func (oMock *MockFilepath) Split(path string) string {
	if oMock.SplitFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.SplitFunc(path)
}

func (oMock *MockFilepath) SplitList(path string) []string {
	if oMock.SplitListFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.SplitListFunc(path)
}

func (oMock *MockFilepath) EvalSymlinks(path string) (string, error) {
	if oMock.EvalSymlinksFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.EvalSymlinksFunc(path)
}

func (oMock *MockFilepath) Glob(pattern string) ([]string, error) {
	if oMock.GlobFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GlobFunc(pattern)
}

func (oMock *MockFilepath) Match(pattern, name string) (bool, error) {
	if oMock.MatchFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.MatchFunc(pattern, name)
}

func (oMock *MockFilepath) Rel(basepath, targpath string) (string, error) {
	if oMock.RelFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.RelFunc(basepath, targpath)
}

func (oMock *MockFilepath) IsAbs(path string) bool {
	if oMock.IsAbsFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.IsAbsFunc(path)
}

func (oMock *MockFilepath) HasPrefix(p, prefix string) bool {
	if oMock.HasPrefixFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.HasPrefixFunc(p, prefix)
}

func (oMock *MockFilepath) IsInDirectory(baseDir, targetPath string) bool {
	if oMock.IsInDirectoryFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.IsInDirectoryFunc(baseDir, targetPath)
}

func (oMock *MockFilepath) VolumeName(path string) string {
	if oMock.VolumeNameFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.VolumeNameFunc(path)
}

type mockOnCallFilepath struct {
	mock *MockFilepath
}

func (o *mockOnCallFilepath) Abs(fn func(path string) (string, error)) {
	o.mock.AbsFunc = fn
}

func (o *mockOnCallFilepath) Clean(fn func(path string) string) {
	o.mock.CleanFunc = fn
}

func (o *mockOnCallFilepath) Dir(fn func(path string) string) {
	o.mock.DirFunc = fn
}

func (o *mockOnCallFilepath) Base(fn func(path string) string) {
	o.mock.BaseFunc = fn
}

func (o *mockOnCallFilepath) Ext(fn func(path string) string) {
	o.mock.ExtFunc = fn
}

func (o *mockOnCallFilepath) FromSlash(fn func(path string) string) {
	o.mock.FromSlashFunc = fn
}

func (o *mockOnCallFilepath) ToSlash(fn func(path string) string) {
	o.mock.ToSlashFunc = fn
}

func (o *mockOnCallFilepath) Join(fn func(elem ...string) string) {
	o.mock.JoinFunc = fn
}

func (o *mockOnCallFilepath) Split(fn func(path string) string) {
	o.mock.SplitFunc = fn
}

func (o *mockOnCallFilepath) SplitList(fn func(path string) []string) {
	o.mock.SplitListFunc = fn
}

func (o *mockOnCallFilepath) EvalSymlinks(fn func(path string) (string, error)) {
	o.mock.EvalSymlinksFunc = fn
}

func (o *mockOnCallFilepath) Glob(fn func(pattern string) ([]string, error)) {
	o.mock.GlobFunc = fn
}

func (o *mockOnCallFilepath) Match(fn func(pattern, name string) (bool, error)) {
	o.mock.MatchFunc = fn
}

func (o *mockOnCallFilepath) Rel(fn func(basepath, targpath string) (string, error)) {
	o.mock.RelFunc = fn
}

func (o *mockOnCallFilepath) IsAbs(fn func(path string) bool) {
	o.mock.IsAbsFunc = fn
}

func (o *mockOnCallFilepath) HasPrefix(fn func(p, prefix string) bool) {
	o.mock.HasPrefixFunc = fn
}

func (o *mockOnCallFilepath) IsInDirectory(fn func(baseDir, targetPath string) bool) {
	o.mock.IsInDirectoryFunc = fn
}

func (o *mockOnCallFilepath) VolumeName(fn func(path string) string) {
	o.mock.VolumeNameFunc = fn
}

type mockSetReturnFilepath struct {
	mock *MockFilepath
}

func (r *mockSetReturnFilepath) Abs(result0 string, err error) {
	r.mock.OnCall.Abs(func(path string) (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnFilepath) Clean(result string) {
	r.mock.OnCall.Clean(func(path string) string {
		return result
	})
}

func (r *mockSetReturnFilepath) Dir(result string) {
	r.mock.OnCall.Dir(func(path string) string {
		return result
	})
}

func (r *mockSetReturnFilepath) Base(result string) {
	r.mock.OnCall.Base(func(path string) string {
		return result
	})
}

func (r *mockSetReturnFilepath) Ext(result string) {
	r.mock.OnCall.Ext(func(path string) string {
		return result
	})
}

func (r *mockSetReturnFilepath) FromSlash(result string) {
	r.mock.OnCall.FromSlash(func(path string) string {
		return result
	})
}

func (r *mockSetReturnFilepath) ToSlash(result string) {
	r.mock.OnCall.ToSlash(func(path string) string {
		return result
	})
}

func (r *mockSetReturnFilepath) Join(result string) {
	r.mock.OnCall.Join(func(elem ...string) string {
		return result
	})
}

func (r *mockSetReturnFilepath) Split(result string) {
	r.mock.OnCall.Split(func(path string) string {
		return result
	})
}

func (r *mockSetReturnFilepath) SplitList(result []string) {
	r.mock.OnCall.SplitList(func(path string) []string {
		return result
	})
}

func (r *mockSetReturnFilepath) EvalSymlinks(result0 string, err error) {
	r.mock.OnCall.EvalSymlinks(func(path string) (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnFilepath) Glob(result0 []string, err error) {
	r.mock.OnCall.Glob(func(pattern string) ([]string, error) {
		return result0, err
	})
}

func (r *mockSetReturnFilepath) Match(result0 bool, err error) {
	r.mock.OnCall.Match(func(pattern, name string) (bool, error) {
		return result0, err
	})
}

func (r *mockSetReturnFilepath) Rel(result0 string, err error) {
	r.mock.OnCall.Rel(func(basepath, targpath string) (string, error) {
		return result0, err
	})
}

func (r *mockSetReturnFilepath) IsAbs(result bool) {
	r.mock.OnCall.IsAbs(func(path string) bool {
		return result
	})
}

func (r *mockSetReturnFilepath) HasPrefix(result bool) {
	r.mock.OnCall.HasPrefix(func(p, prefix string) bool {
		return result
	})
}

func (r *mockSetReturnFilepath) IsInDirectory(result bool) {
	r.mock.OnCall.IsInDirectory(func(baseDir, targetPath string) bool {
		return result
	})
}

func (r *mockSetReturnFilepath) VolumeName(result string) {
	r.mock.OnCall.VolumeName(func(path string) string {
		return result
	})
}
