// Code generated by xmocks; DO NOT EDIT.
package mocks

import (
	"fmt"
	"io"
	"runtime"
)

type TestCaseIO struct {
	Name        string
	Env         map[string]string
	Input       any
	Want        any
	WantErr     bool
	ErrContains string
	MockFn      func(m *MockIO)
}

func NewMockIO() *MockIO {
	mock := &MockIO{}
	mock.OnCall = &mockOnCallIO{mock: mock}
	mock.SetReturn = &mockSetReturnIO{mock: mock}
	return mock
}

type MockIO struct {
	CopyFunc        func(dst io.Writer, src io.Reader) (int64, error)
	CopyBufferFunc  func(dst io.Writer, src io.Reader, buf []byte) (int64, error)
	CopyNFunc       func(dst io.Writer, src io.Reader, n int64) (int64, error)
	ReadAllFunc     func(r io.Reader) ([]byte, error)
	ReadAtLeastFunc func(r io.Reader, buf []byte, min int) (int, error)
	ReadFullFunc    func(r io.Reader, buf []byte) (int, error)
	WriteStringFunc func(w io.Writer, s string) (int, error)
	LimitReaderFunc func(r io.Reader, n int64) io.Reader
	MultiReaderFunc func(readers ...io.Reader) io.Reader
	MultiWriterFunc func(writers ...io.Writer) io.Writer
	TeeReaderFunc   func(r io.Reader, w io.Writer) io.Reader
	NopCloserFunc   func(r io.Reader) io.ReadCloser
	OnCall          *mockOnCallIO
	SetReturn       *mockSetReturnIO
}

func (m *MockIO) panicIfNotConfigured() {
	pc, _, _, ok := runtime.Caller(2)
	methodName := "UnknownMethod"
	if ok {
		fullFnName := runtime.FuncForPC(pc).Name()
		shortName := fullFnName
		for i := len(fullFnName) - 1; i >= 0; i-- {
			if fullFnName[i] == '/' {
				shortName = fullFnName[i+1:]
				break
			}
		}
		methodName = shortName
	}
	panic(fmt.Sprintf("CRITICAL: Mock for %s not configured.", methodName))
}

func (oMock *MockIO) Copy(dst io.Writer, src io.Reader) (int64, error) {
	if oMock.CopyFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.CopyFunc(dst, src)
}

func (oMock *MockIO) CopyBuffer(dst io.Writer, src io.Reader, buf []byte) (int64, error) {
	if oMock.CopyBufferFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.CopyBufferFunc(dst, src, buf)
}

func (oMock *MockIO) CopyN(dst io.Writer, src io.Reader, n int64) (int64, error) {
	if oMock.CopyNFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.CopyNFunc(dst, src, n)
}

func (oMock *MockIO) ReadAll(r io.Reader) ([]byte, error) {
	if oMock.ReadAllFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ReadAllFunc(r)
}

func (oMock *MockIO) ReadAtLeast(r io.Reader, buf []byte, min int) (int, error) {
	if oMock.ReadAtLeastFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ReadAtLeastFunc(r, buf, min)
}

func (oMock *MockIO) ReadFull(r io.Reader, buf []byte) (int, error) {
	if oMock.ReadFullFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.ReadFullFunc(r, buf)
}

func (oMock *MockIO) WriteString(w io.Writer, s string) (int, error) {
	if oMock.WriteStringFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.WriteStringFunc(w, s)
}

func (oMock *MockIO) LimitReader(r io.Reader, n int64) io.Reader {
	if oMock.LimitReaderFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.LimitReaderFunc(r, n)
}

func (oMock *MockIO) MultiReader(readers ...io.Reader) io.Reader {
	if oMock.MultiReaderFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.MultiReaderFunc(readers...)
}

func (oMock *MockIO) MultiWriter(writers ...io.Writer) io.Writer {
	if oMock.MultiWriterFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.MultiWriterFunc(writers...)
}

func (oMock *MockIO) TeeReader(r io.Reader, w io.Writer) io.Reader {
	if oMock.TeeReaderFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.TeeReaderFunc(r, w)
}

func (oMock *MockIO) NopCloser(r io.Reader) io.ReadCloser {
	if oMock.NopCloserFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.NopCloserFunc(r)
}

type mockOnCallIO struct {
	mock *MockIO
}

func (o *mockOnCallIO) Copy(fn func(dst io.Writer, src io.Reader) (int64, error)) {
	o.mock.CopyFunc = fn
}

func (o *mockOnCallIO) CopyBuffer(fn func(dst io.Writer, src io.Reader, buf []byte) (int64, error)) {
	o.mock.CopyBufferFunc = fn
}

func (o *mockOnCallIO) CopyN(fn func(dst io.Writer, src io.Reader, n int64) (int64, error)) {
	o.mock.CopyNFunc = fn
}

func (o *mockOnCallIO) ReadAll(fn func(r io.Reader) ([]byte, error)) {
	o.mock.ReadAllFunc = fn
}

func (o *mockOnCallIO) ReadAtLeast(fn func(r io.Reader, buf []byte, min int) (int, error)) {
	o.mock.ReadAtLeastFunc = fn
}

func (o *mockOnCallIO) ReadFull(fn func(r io.Reader, buf []byte) (int, error)) {
	o.mock.ReadFullFunc = fn
}

func (o *mockOnCallIO) WriteString(fn func(w io.Writer, s string) (int, error)) {
	o.mock.WriteStringFunc = fn
}

func (o *mockOnCallIO) LimitReader(fn func(r io.Reader, n int64) io.Reader) {
	o.mock.LimitReaderFunc = fn
}

func (o *mockOnCallIO) MultiReader(fn func(readers ...io.Reader) io.Reader) {
	o.mock.MultiReaderFunc = fn
}

func (o *mockOnCallIO) MultiWriter(fn func(writers ...io.Writer) io.Writer) {
	o.mock.MultiWriterFunc = fn
}

func (o *mockOnCallIO) TeeReader(fn func(r io.Reader, w io.Writer) io.Reader) {
	o.mock.TeeReaderFunc = fn
}

func (o *mockOnCallIO) NopCloser(fn func(r io.Reader) io.ReadCloser) {
	o.mock.NopCloserFunc = fn
}

type mockSetReturnIO struct {
	mock *MockIO
}

func (r *mockSetReturnIO) Copy(result0 int64, err error) {
	r.mock.OnCall.Copy(func(dst io.Writer, src io.Reader) (int64, error) {
		return result0, err
	})
}

func (r *mockSetReturnIO) CopyBuffer(result0 int64, err error) {
	r.mock.OnCall.CopyBuffer(func(dst io.Writer, src io.Reader, buf []byte) (int64, error) {
		return result0, err
	})
}

func (r *mockSetReturnIO) CopyN(result0 int64, err error) {
	r.mock.OnCall.CopyN(func(dst io.Writer, src io.Reader, n int64) (int64, error) {
		return result0, err
	})
}

func (r *mockSetReturnIO) ReadAll(result0 []byte, err error) {
	r.mock.OnCall.ReadAll(func(r io.Reader) ([]byte, error) {
		return result0, err
	})
}

func (r *mockSetReturnIO) ReadAtLeast(result0 int, err error) {
	r.mock.OnCall.ReadAtLeast(func(r io.Reader, buf []byte, min int) (int, error) {
		return result0, err
	})
}

func (r *mockSetReturnIO) ReadFull(result0 int, err error) {
	r.mock.OnCall.ReadFull(func(r io.Reader, buf []byte) (int, error) {
		return result0, err
	})
}

func (r *mockSetReturnIO) WriteString(result0 int, err error) {
	r.mock.OnCall.WriteString(func(w io.Writer, s string) (int, error) {
		return result0, err
	})
}

func (r *mockSetReturnIO) LimitReader(result io.Reader) {
	r.mock.OnCall.LimitReader(func(r io.Reader, n int64) io.Reader {
		return result
	})
}

func (r *mockSetReturnIO) MultiReader(result io.Reader) {
	r.mock.OnCall.MultiReader(func(readers ...io.Reader) io.Reader {
		return result
	})
}

func (r *mockSetReturnIO) MultiWriter(result io.Writer) {
	r.mock.OnCall.MultiWriter(func(writers ...io.Writer) io.Writer {
		return result
	})
}

func (r *mockSetReturnIO) TeeReader(result io.Reader) {
	r.mock.OnCall.TeeReader(func(r io.Reader, w io.Writer) io.Reader {
		return result
	})
}

func (r *mockSetReturnIO) NopCloser(result io.ReadCloser) {
	r.mock.OnCall.NopCloser(func(r io.Reader) io.ReadCloser {
		return result
	})
}
