// Code generated by xmocks; DO NOT EDIT.
package mocks

import (
	"fmt"
	"runtime"
)

type TestCaseRuntime struct {
	Name        string
	Env         map[string]string
	Input       any
	Want        any
	WantErr     bool
	ErrContains string
	MockFn      func(m *MockRuntime)
}

func NewMockRuntime() *MockRuntime {
	mock := &MockRuntime{}
	mock.OnCall = &mockOnCallRuntime{mock: mock}
	mock.SetReturn = &mockSetReturnRuntime{mock: mock}
	return mock
}

type MockRuntime struct {
	GOOSFunc         func() string
	GOARCHFunc       func() string
	NumCPUFunc       func() int
	VersionFunc      func() string
	NumGoroutineFunc func() int
	ReadMemStatsFunc func(m *runtime.MemStats)
	GCFunc           func()
	StackFunc        func(buf []byte, all bool) int
	CallerFunc       func(skip int) (uintptr, string, int, bool)
	OnCall           *mockOnCallRuntime
	SetReturn        *mockSetReturnRuntime
}

func (m *MockRuntime) panicIfNotConfigured() {
	pc, _, _, ok := runtime.Caller(2)
	methodName := "UnknownMethod"
	if ok {
		fullFnName := runtime.FuncForPC(pc).Name()
		shortName := fullFnName
		for i := len(fullFnName) - 1; i >= 0; i-- {
			if fullFnName[i] == '/' {
				shortName = fullFnName[i+1:]
				break
			}
		}
		methodName = shortName
	}
	panic(fmt.Sprintf("CRITICAL: Mock for %s not configured.", methodName))
}

func (oMock *MockRuntime) GOOS() string {
	if oMock.GOOSFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GOOSFunc()
}

func (oMock *MockRuntime) GOARCH() string {
	if oMock.GOARCHFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.GOARCHFunc()
}

func (oMock *MockRuntime) NumCPU() int {
	if oMock.NumCPUFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.NumCPUFunc()
}

func (oMock *MockRuntime) Version() string {
	if oMock.VersionFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.VersionFunc()
}

func (oMock *MockRuntime) NumGoroutine() int {
	if oMock.NumGoroutineFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.NumGoroutineFunc()
}

func (oMock *MockRuntime) ReadMemStats(m *runtime.MemStats) {
	if oMock.ReadMemStatsFunc == nil {
		oMock.panicIfNotConfigured()
	}
	oMock.ReadMemStatsFunc(m)
}

func (oMock *MockRuntime) GC() {
	if oMock.GCFunc == nil {
		oMock.panicIfNotConfigured()
	}
	oMock.GCFunc()
}

func (oMock *MockRuntime) Stack(buf []byte, all bool) int {
	if oMock.StackFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.StackFunc(buf, all)
}

func (oMock *MockRuntime) Caller(skip int) (uintptr, string, int, bool) {
	if oMock.CallerFunc == nil {
		oMock.panicIfNotConfigured()
	}
	return oMock.CallerFunc(skip)
}

type mockOnCallRuntime struct {
	mock *MockRuntime
}

func (o *mockOnCallRuntime) GOOS(fn func() string) {
	o.mock.GOOSFunc = fn
}

func (o *mockOnCallRuntime) GOARCH(fn func() string) {
	o.mock.GOARCHFunc = fn
}

func (o *mockOnCallRuntime) NumCPU(fn func() int) {
	o.mock.NumCPUFunc = fn
}

func (o *mockOnCallRuntime) Version(fn func() string) {
	o.mock.VersionFunc = fn
}

func (o *mockOnCallRuntime) NumGoroutine(fn func() int) {
	o.mock.NumGoroutineFunc = fn
}

func (o *mockOnCallRuntime) ReadMemStats(fn func(m *runtime.MemStats)) {
	o.mock.ReadMemStatsFunc = fn
}

func (o *mockOnCallRuntime) GC(fn func()) {
	o.mock.GCFunc = fn
}

func (o *mockOnCallRuntime) Stack(fn func(buf []byte, all bool) int) {
	o.mock.StackFunc = fn
}

func (o *mockOnCallRuntime) Caller(fn func(skip int) (uintptr, string, int, bool)) {
	o.mock.CallerFunc = fn
}

type mockSetReturnRuntime struct {
	mock *MockRuntime
}

func (r *mockSetReturnRuntime) GOOS(result string) {
	r.mock.OnCall.GOOS(func() string {
		return result
	})
}

func (r *mockSetReturnRuntime) GOARCH(result string) {
	r.mock.OnCall.GOARCH(func() string {
		return result
	})
}

func (r *mockSetReturnRuntime) NumCPU(result int) {
	r.mock.OnCall.NumCPU(func() int {
		return result
	})
}

func (r *mockSetReturnRuntime) Version(result string) {
	r.mock.OnCall.Version(func() string {
		return result
	})
}

func (r *mockSetReturnRuntime) NumGoroutine(result int) {
	r.mock.OnCall.NumGoroutine(func() int {
		return result
	})
}

func (r *mockSetReturnRuntime) ReadMemStats() {
	r.mock.OnCall.ReadMemStats(func(m *runtime.MemStats) {
	})
}

func (r *mockSetReturnRuntime) GC() {
	r.mock.OnCall.GC(func() {
	})
}

func (r *mockSetReturnRuntime) Stack(result int) {
	r.mock.OnCall.Stack(func(buf []byte, all bool) int {
		return result
	})
}

func (r *mockSetReturnRuntime) Caller(result0 uintptr, result1 string, result2 int, result3 bool) {
	r.mock.OnCall.Caller(func(skip int) (uintptr, string, int, bool) {
		return result0, result1, result2, result3
	})
}
