name: Auto Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Commit Message and Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Captures the last commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"

          # Checks if the message starts with 'release: v' (e.g., release: v1.0.0)
          if [[ "$COMMIT_MSG" =~ ^release:\ (v[0-9]+\.[0-9]+\.[0-9]+.*)$ ]]; then
            # Extracts the tag from the message (e.g., v1.0.0)
            TAG="${BASH_REMATCH[1]}"
            echo ":: Tag detected: $TAG"

            # Configures Git for the operation
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@://github.com"

            # Creates and pushes the tag to GitHub
            git tag "$TAG"
            git push origin "$TAG"
            echo ":: Tag $TAG successfully created and published!"
          else
            echo ":: Standard commit detected. No tag will be created."
          fi
